services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - auth
      - serv_a
      - serv_b
    networks:
      - appnet

  auth:
    build: ./auth
    container_name: auth
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/authdb
      SPRING_DATASOURCE_USERNAME: authuser
      SPRING_DATASOURCE_PASSWORD: authpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_SQL_INIT_MODE: never
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      APP_PUBLIC_BASE_URL: http://localhost:8080
      SPRING_PROFILES_ACTIVE: docker
    expose:
      - "8080"
    depends_on:
      - rabbitmq
    networks:
      - appnet

  notification:
    build: ./notification
    container_name: notification
    ports:
      - "8081:8080"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025
      APP_PUBLIC_BASE_URL: http://localhost:8080
      APP_MAIL_FROM: no-reply@m1.local
    depends_on:
      - rabbitmq
      - mailhog
    networks:
      - appnet

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - appnet

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - appnet

  serv_a:
    build: ./servA
    container_name: serva
    expose:
      - "8080"
    networks:
      - appnet

  serv_b:
    build: ./servB
    container_name: servb
    expose:
      - "8080"
    networks:
      - appnet

  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  db-data:
